Repository patrickfcf/UniRent, pull requests merged in 2018-05, with the labels that each got.

#22 Production add max lenght
  beta/add-listings.php
  beta/add-listings_EN.php
  beta/contact-us.php
  beta/how-it-works.php
  beta/listings.php
  beta/pricing-table.php
  beta/pricing-table_EN.php
  beta/profile.php
  beta/profile_EN.php
  beta/sign-up.php
  beta/sign-up_EN.php
  beta/terms-of-services.php
Labels: enhancement

#26 Productio
  beta/terms-of-services_EN.php
Labels: good first issue

#25 Verificação e Correção de todas as páginas em PT
  beta/add-listings.php
  beta/how-it-works.php
  beta/index.php
  beta/index_EN.php
  beta/itens_history.php
  beta/listings.php
  beta/listings_EN.php
  beta/manage_ads.php
  beta/my_rentals.php
  beta/php/footer.php
  beta/php/header_listings.php
  beta/php/header_listings_index.php
  beta/pricing-table.php
  beta/sign-up.php
  beta/terms-of-services.php
Labels: good first issue

#27 3º correção dashboard
  beta/dashboard.php
  beta/dashboard_EN.php
Labels: bug
